### ISSUE TITLE
SMTP does not work...

### ISSUE THREAD

**Issue by marcogaio** [ClaperCo/Claper#112]
I'm testing Claper (wondeful!) for a Linux User group here in north east of Italy (Pordenone Linux User Group, PNLug).

I was able to run the docker container, fix some issue putting it behind a nginx reverse proxy (if needed, i can provide feedback on that, because i've not found info on documents) but still Claper does not send email.

Docker VM is part of a little virtualization setup, where there's also an SMTP server/relay that send email for all the services. I've setup `.env` as:
```
SMTP_RELAY=10.21.13.180
SMTP_AUTH=never
SMTP_PORT=25
SMTP_TLS=never
SMTP_SSL=false
```

But email does not get sent; even, i've sniffed on network interfaces, end there's even NO SMTP traffic, so Claper seems never **tries to** send email...

Network and SMTP server reachability seems fine:

```
root@vdockerpnlug1:~# docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED        STATUS                  PORTS                                       NAMES
ff6a3668b491   ghcr.io/claperco/claper:latest   "sh -c '/app/bin/cla…"   20 hours ago   Up 20 hours (healthy)   0.0.0.0:4000->4000/tcp, :::4000->4000/tcp   claper-app-1
dddc4a72e4f4   postgres:15                      "docker-entrypoint.s…"   20 hours ago   Up 20 hours (healthy)   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp   claper-db-1
root@vdockerpnlug1:~# docker exec -it  ff6a3668b491 bash
ff6a3668b491:/app# nc 10.21.13.180 25
220 mail.artemis.pnlug.it ESMTP Exim 4.94.2 Mon, 14 Oct 2024 14:17:05 +0200
help
214-Commands supported:
214 AUTH STARTTLS HELO EHLO MAIL RCPT DATA BDAT NOOP QUIT RSET HELP
quit
221 mail.artemis.pnlug.it closing connection
```

What i'm doing wrong?! Thanks.

**Comment by alxlion** [comment]
Ciao Marco!

Claper doesn't send a lot of emails, it only sends an email when
- You request a password change 
- Add a facilitator when you edit/create an event


Have you tried this to test your smtp configuration?

**Comment by marcogaio** [comment]
Sorry, forgot a piece; my complete email configuration in `.env ' is:
```
MAIL_TRANSPORT=smtp
MAIL_FROM=tech@pnlug.it
MAIL_FROM_NAME=Claper

SMTP_RELAY=10.21.13.180
SMTP_AUTH=never
SMTP_PORT=25
SMTP_TLS=never
SMTP_SSL=false
```

I've tried to:
1. change my password
2. change my email
3. reset my password

no email get sent...

**Comment by marcogaio** [comment]
> Claper doesn't send a lot of emails, it only sends an email when

Sorry, forgot to say.

So there's no __confirmation__ mechanism for user creation? This cannot lead to __user creation bombing__ attacks?

**Comment by alxlion** [comment]
Email is always a pain to manage, so we try to avoid it at all costs. We use anti-bot and anti-spam on the frontend of our instance to avoid any bombing. 

Regarding your issue, are you sure that the container has access to `10.21.13.180`?

**Comment by marcogaio** [comment]
> Email is always a pain to manage, so we try to avoid it at all costs. We use anti-bot and anti-spam on the frontend of our instance to avoid any bombing.

Ok... have some example configuration/hint/... to share? Thanks.
 
> Regarding your issue, are you sure that the container has access to `10.21.13.180`?

Sure! As you can see in my first post, i spawned a shell into the claper container and  accessed the mail server.

**Comment by alxlion** [comment]
We just added `EMAIL_CONFIRMATION` to enable email confirmation at registration if you need so (https://docs.claper.co/self-hosting/configuration.html#email-confirmation).

Do you have any app logs in Claper to share?

**Comment by marcogaio** [comment]
> We just added `EMAIL_CONFIRMATION` to enable email confirmation at registration if you need so (https://docs.claper.co/self-hosting/configuration.html#email-confirmation) (available on the dev version).

I've stopped, updated and restarted the container, setting that variable in `.env`; nothing changed...

> Do you have any app logs in Claper to share?

Do you mean the log i can obtain with `docker logs --follow e9e6c0a6cc8b '? Seems me contain nothing more then HTTP GET and WebSocket request.

**Comment by alxlion** [comment]
Sorry for the late reply, I am trying to reproduce this and investigate

**Comment by bethgocs** [comment]
same issue

**Comment by alxlion** [comment]
In the `dev` branch, a new mail job handling system has been implemented, which will show error logs in the console if something doesn't work properly:

```[info] {"error":"** (Oban.PerformError) Claper.Workers.Mailers failed with {:error, {:retries_exceeded, {:network_failure, ~c\"localhost\", {:error, {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}}}}}","args":{"email":"test@test.com","event_name":"hello","type":"event_invitation","url":"http://localhost:4000/events"},"id":13,"meta":{},"state":"failure","max_attempts":20,"queue":"mailers","worker":"Claper.Workers.Mailers","source":"oban","event":"job:exception","duration":97637,"queue_time":1036380,"attempt":6,"tags":[]}```

You can test and come back here with the message log.

**Comment by bethgocs** [comment]
Hope this will help 

app-1  | 09:02:53.279 [info] {"args":{"type":"reset","url":"http://***/users/reset_password/***","user_id":1},"id":1,"meta":{},"system_time":1734858173278930823,"max_attempts":20,"queue":"mailers","worker":"Claper.Workers.Mailers","source":"oban","event":"job:start","attempt":3,"tags":[]}
app-1  | 09:02:53.294 [info] {"error":"** (Oban.PerformError) Claper.Workers.Mailers failed with {:error, {:retries_exceeded, {:network_failure, ~c\"mail.***\", {:error, {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}}}}}","args":{"type":"reset","url":"http://***/users/reset_password/***","user_id":1},"id":1,"meta":{},"state":"failure","max_attempts":20,"queue":"mailers","worker":"Claper.Workers.Mailers","source":"oban","duration":12833,"event":"job:exception","queue_time":57686,"attempt":3,"tags":[]}

**Comment by alxlion** [comment]
> Hope this will help. Tried it on Port 25 and 465. Also successfully send a mail with netcat (https://learn.microsoft.com/de-de/exchange/use-telnet-to-test-smtp-communication-exchange-2013-help). Mailserver works and reachable.
> 
> 
> 
> app-1  | 09:02:53.279 [info] {"args":{"type":"reset","url":"http://***/users/reset_password/***","user_id":1},"id":1,"meta":{},"system_time":1734858173278930823,"max_attempts":20,"queue":"mailers","worker":"Claper.Workers.Mailers","source":"oban","event":"job:start","attempt":3,"tags":[]}
> 
> app-1  | 09:02:53.294 [info] {"error":"** (Oban.PerformError) Claper.Workers.Mailers failed with {:error, {:retries_exceeded, {:network_failure, ~c\"mail.***\", {:error, {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}}}}}","args":{"type":"reset","url":"http://***/users/reset_password/***","user_id":1},"id":1,"meta":{},"state":"failure","max_attempts":20,"queue":"mailers","worker":"Claper.Workers.Mailers","source":"oban","duration":12833,"event":"job:exception","queue_time":57686,"attempt":3,"tags":[]}
> 
> 

Thanks I will investigate further, can you provide me your docker compose and details about your smtp server like TLS/SSL, service used (postfix or any other) to help me reproduce it on my side ? Thanks

**Comment by bethgocs** [comment]
> Thanks I will investigate further, can you provide me your docker compose and details about your smtp server like TLS/SSL, service used (postfix or any other) to help me reproduce it on my side ? Thanks

Hi here is the requested Information... I use Mailcow (Postfix) as MTA

docker-compose.yaml
[...]
  app:
    #image: ghcr.io/claperco/claper:latest # or build: .
    image: ghcr.io/claperco/claper:dev # or build: .
    ports:
      - 127.0.0.1:4000:4000
    restart: unless-stopped
    volumes:
      - "./claper-uploads:/app/uploads"
    healthcheck:
      test: curl --fail http://localhost:4000 || exit 1
      retries: 3
      start_period: 20s
      timeout: 5s
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.poll.rule=Host(`*.****.**`)"
      - "traefik.http.routers.poll.entrypoints=websecure"
      - "traefik.http.routers.poll.tls.certresolver=le"
      - 'traefik.http.services.poll.loadbalancer.server.port=4000'
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - traefik
[...]

.env
# Mail configuration

MAIL_TRANSPORT=smtp
MAIL_FROM=noreply@****.**
#MAIL_FROM=noreply@****.**
MAIL_FROM_NAME=Claper

SMTP_RELAY=mail.****.**
#SMTP_RELAY=10.0.1.1
SMTP_USERNAME=noreply@***.**
SMTP_PASSWORD=***
#SMTP_AUTH=always
SMTP_AUTH=if_available
#SMTP_PORT=465
SMTP_PORT=25
#SMTP_TLS=never
#SMTP_TLS=always
SMTP_TLS=if_available

ENABLE_ACCOUNT_CREATION=false
EMAIL_CONFIRMATION=false

Tried any of These Option in a lot of combinations

root@***:/opt/claper# docker compose exec app sh
/app # nc ***.***.*** 25
220 ***.***.*** ESMTP Postcow

**Comment by alxlion** [comment]
Thanks, I have reproduced it successfully, I'm working on a fix

**Comment by bethgocs** [comment]
Yes thank you!

**Comment by bethgocs** [comment]
Hi, guess you changed the mailserver FQDN in the dev branch to a fixed value for testing?

app-1  | 15:17:08.427 [info] {"error":"** (Oban.PerformError) Claper.Workers.Mailers failed with {:error, {:no_more_hosts, {:permanent_failure, ~c\"**pixel.mxrouting.net**\", :auth_failed}}}","args":{"type":"reset","url":"http://***.***-**/users/reset_password/***","user_id":1},"id":24,"meta":{},"state":"failure","max_attempts":20,"queue":"mailers","worker":"Claper.Workers.Mailers","source":"oban","duration":572826,"event":"job:exception","queue_time":998979,"attempt":2,"tags":[]}

**Comment by alxlion** [comment]
Yes i completely messed up configuration 🤦‍♂️  I reverted it (will be available in few minutes)

**Comment by bethgocs** [comment]
Now I get...

app-1  | 15:37:49.120 [info] {"error":"** (Oban.PerformError) Claper.Workers.Mailers failed with {:error, {:retries_exceeded, {:network_failure, ~c\"***\", {:error, {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}}}}}","args":{"type":"reset","url":"http://***/users/reset_password/***","user_id":1},"id":26,"meta":{},"state":"failure","max_attempts":20,"queue":"mailers","worker":"Claper.Workers.Mailers","source":"oban","duration":11284,"event":"job:exception","queue_time":9547,"attempt":1,"tags":[]}

**Comment by alxlion** [comment]
Yes, the problem is not solved, I'm working on it. It's a problem that affects TLS/SSL connection with SMTP in the Elixir `gen_smtp` dependency (https://github.com/gen-smtp/gen_smtp/issues/328), it's not related to the Claper source, but I'm trying to work on a fix.

**Comment by bethgocs** [comment]
Is it TLS/SSL related? Should "SMTP_TLS=never" help? This also does not work for me.

**Comment by alxlion** [comment]
I have fixed the problem, I am able to send mail through STARTTLS server.

The configuration has been simplified, you only need these four variables:

```
SMTP_RELAY=xx.example.com
SMTP_USERNAME=johndoe@example.com
SMTP_PASSWORD=xxx
SMTP_PORT=587
```

Let me know if this works for you.

**Comment by bethgocs** [comment]
Hi, can confirm that you did a great job. It is now works for me :)

**Comment by alxlion** [comment]
Great ! Thanks for your feedback

**Comment by marcogaio** [comment]
OK, i've tried also i, but seems that something is still broken:
```
08:18:46.212 [error] #PID<0.3023.0> running ClaperWeb.Endpoint (connection #PID<0.3022.0>, stream id 1) terminated
Server: chiedi.pnlug.it:80 (http)
Request: POST /users/reset_password
** (exit) an exception was raised:
    ** (ArgumentError) username is not configured properly,
got: nil, expected a string

        (swoosh 1.16.3) lib/swoosh/adapters/smtp.ex:103: Swoosh.Adapters.SMTP.enforce_type!/2
        (elixir 1.16.0) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
        (elixir 1.16.0) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
        (swoosh 1.16.3) lib/swoosh/adapters/smtp.ex:59: Swoosh.Adapters.SMTP.deliver/2
        (claper 2.2.0) lib/claper/mailer.ex:2: anonymous fn/2 in Claper.Mailer.instrument/3
        (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (claper 2.2.0) lib/claper/accounts/user_notifier.ex:56: Claper.Accounts.UserNotifier.deliver_reset_password_instructions/2
        (claper 2.2.0) lib/claper_web/controllers/user_reset_password_controller.ex:16: ClaperWeb.UserResetPasswordController.create/2
```

Seems to me that claper expect an username to send email but i've an internal relay that handle email, so there's no username; i've in `.env`:

```
MAIL_TRANSPORT=smtp
MAIL_FROM=tech@pnlug.it
MAIL_FROM_NAME=Claper

SMTP_RELAY=10.21.13.180
SMTP_AUTH=never
SMTP_PORT=25
SMTP_TLS=never
SMTP_SSL=false

EMAIL_CONFIRMATION=true
```

Thanks.

**Comment by alxlion** [comment]
You can try again using the latest `dev` image. You only need: 

```
SMTP_RELAY=10.21.13.180
SMTP_PORT=25
```

**Comment by marcogaio** [comment]
Tried but:

```
17:12:20.521 [notice] TLS :client: In state :wait_cert at ssl_handshake.erl:2135 generated CLIENT ALERT: Fatal - Handshake Failure
 - {:bad_cert, :hostname_check_failed}
17:12:20.530 [info] {"error":"** (Oban.PerformError) Claper.Workers.Mailers failed with {:error, %Mua.TransportError{reason: {:tls_alert, {:handshake_failure, ~c\"TLS client: In state wait_cert at ssl_handshake.erl:2135 generated CLIENT ALERT: Fatal - Handshake Failure\\n {bad_cert,hostname_check_failed}\"}}}}","args":{"type":"reset","url":"https://chiedi.pnlug.it/users/reset_password/<ascii_glbberish>","user_id":4},"id":3,"meta":{},"state":"failure","max_attempts":20,"queue":"mailers","worker":"Claper.Workers.Mailers","source":"oban","duration":42765,"event":"job:exception","attempt":5,"queue_time":59497172,"tags":[]}
```

The SMTP server have a cert, but does not require it. Seems Claper that insist to use SSL/TLS (in strict mode, eg with host verification) and fail.

I've set:
```
SMTP_AUTH=never
SMTP_PORT=25
SMTP_TLS=never
SMTP_SSL=false
```
but claper seems to ignore it...

**Comment by E-J-D** [comment]
Hi folks,

my mail configuration is this...

# Mail configuration
MAIL_TRANSPORT=smtp
MAIL_FROM=noreply@do*******.com
MAIL_FROM_NAME=My Claper

SMTP_RELAY=smtp.strato.de
SMTP_USERNAME=noreply@do*******.com
SMTP_PASSWORD=verystrong
SMTP_PORT=465

I sent emails from this address with Thunderbird. Worked as expected. In addition to Claper, Thunderbird configured the SMTP with...
authentication method = Password, normal 
connection security = SSL/TLS

The container is up and running and I can ping the smtp.strato.de from within the container.

The log shows this error:

```
15:58:54.829 [info] {"error":"** (Oban.PerformError) Claper.Workers.Mailers failed with {:error, %Mua.TransportError{reason: :timeout}}","args":{"type":"confirm","url":"http://192.168.22.18:4000/users/confirm/j5wTnTEeGlimW0J0u53P3hRKS4mjXHAtNjFBP0M9lkg","user_id":2},"id":2,"meta":{},"state":"failure","max_attempts":20,"queue":"mailers","worker":"Claper.Workers.Mailers","source":"oban","duration":30016340,"event":"job:exception","queue_time":799686,"attempt":2,"tags":[]}
```

Any ideas?

**Comment by E-J-D** [comment]
oooooooh, I changed the port to 587 as I just learned, that Strato does support STARTTLS on 587 as well. Now it works.

**Comment by alxlion** [comment]
From what I can see, most of you here use port 465. This port has officially been deprecated since 1998 in favor of port 587, which is now used by most SMTP services.

Those who are trying to connect with 465 should try 587 to see if they have the same problem.

However, the connection to an unsecured server on port 25 still needs to be tested. I don't know if this is a widespread problem or a common use case.

Thanks for all your feedback on this issue 🙏

**Comment by E-J-D** [comment]
As writen in https://github.com/ClaperCo/Claper/issues/112#issuecomment-2879869327...

I changed the port to 587 and I learned that this works with Strato as well. This issue is closed for me.

**Comment by marcogaio** [comment]
> However, the connection to an unsecured server on port 25 still needs to be tested. I don't know if this is a widespread problem or a common use case.

Still does not work. Just tried:
```
19:46:30.176 [notice] TLS :client: In state :wait_cert at ssl_handshake.erl:2135 generated CLIENT ALERT: Fatal - Handshake Failure
 - {:bad_cert, :hostname_check_failed}
```

Consider that in simple setup is common to use an account to send email; but in mid-complex setup (like mine) simply i've setup a SMTP server and all services use (in a local, private network) the service to send email, leaving to SMTP server all authentication and reputation trouble.

In this setup, i'm forced to create an account only to be able to authenticate Claper and permit them to send email; it is totally unneeded (i can trust claper in my private network, i don't need to auth them).

If i can be useful in some way, say me. Thanks.

**Comment by marcogaio** [comment]
OK, i've circumvent the problem.

Reading logs as:
```
13:27:41.133 [info] {"args":{"type":"reset","url":"https://chiedi.pnlug.it/users/reset_password/_garbbaggeeeeeeee","user_id":4},"id":7,"meta":{},"system_time":1752413261132839635,"max_attempts":20,"queue":"mailers","worker":"Claper.Workers.Mailers","source":"oban","event":"job:start","attempt":5,"tags":[]}
13:27:41.165 [notice] TLS :client: In state :wait_cert at ssl_handshake.erl:2135 generated CLIENT ALERT: Fatal - Handshake Failure
 - {:bad_cert, :hostname_check_failed}
```

Lead me to the idea that claper check also the corrispondance of the certificate CN and the hostname, so if i put internal address does not work (because does not match with the certificate) and if i put esterna address does not work (because external address are not meant to receive email in this way).

I've simply used the bind feature __RPZ__ (https://www.redpill-linpro.com/techblog/2015/12/08/dns-rpz.html) to override external hostname with local address, and voilà, all works as expected.

My current configuration is:
```
SMTP_RELAY=mail.pnlug.it
SMTP_AUTH=never
SMTP_PORT=25
SMTP_TLS=never
SMTP_SSL=false
```

I think one more parameter have to be addedd, `SMTP_CERT_IGNORE=true` to ignore every certificate errors.

**Comment by alxlion** [comment]
Hey @marcogaio, thanks for the troubleshooting.

Yes, ignoring the certificate is essential for your kind of network architecture, it's on the way!

**Comment by marcogaio** [comment]
_it has not had recent activity_ because:

> Yes, ignoring the certificate is essential for your kind of network architecture, it's on the way!

I'm waiting _that_ way...

[ OK, a dumb comment to keep bug alive ;-) ]

**Comment by marcogaio** [comment]
> Yes, ignoring the certificate is essential for your kind of network architecture, it's on the way!

I'm waiting _that_ way...

[ OK, a dumb comment to keep bug alive ;-) ]

**Comment by raulrpearson** [comment]
@marcogaio, I'm hoping PR #197 will make it possible for you to finally fix your setup. If you have the chance to check it out, please do. The Mailpit example might map best to your use case:

```shell
SMTP_RELAY=localhost
SMTP_PORT=1025
SMTP_NO_MX_LOOKUPS=true
SMTP_AUTH=never
SMTP_SSL=false
SMTP_TLS=never
```

If this still doesn't fix the problem, let me know and we can see what else we can do.

**Comment by marcogaio** [comment]
It worked! Thanks!

**Comment by nmbgeek** [comment]
I am not able to get email to work using either the Microsoft 365 Connector relay nor our Amazon SES SMTP.  I have dozens of services using these but I am having no success with Claper.  I have also tried some of the undocumented SMTP variables without luck either that I have found here and seen referenced prior in this thread - https://github.com/search?q=repo%3AClaperCo%2FClaper%20SMTP_AUTH&type=code
